export const userInfoBlock: string;
export const userInfo: string;
export const userName: string;
export const preview: string;
export const loading: string;
export const userIcon: string;
export const blick: string;
export const leaveIcon: string;
export const authButtonContainer: string;
