export const BOTS_GET_START: 'BOTS_GET_START' = 'BOTS_GET_START';
export const BOTS_GET_ERROR: 'BOTS_GET_ERROR' = 'BOTS_GET_ERROR';
export const BOTS_GET_SUCCESS: 'BOTS_GET_SUCCESS' = 'BOTS_GET_SUCCESS';

export const BOT_CREATE_START: 'BOT_CREATE_START' = 'BOT_CREATE_START';
export const BOT_CREATE_ERROR: 'BOT_CREATE_ERROR' = 'BOT_CREATE_ERROR';
export const BOT_CREATE_SUCCESS: 'BOT_CREATE_SUCCESS' = 'BOT_CREATE_SUCCESS';
