export const BOTS_GET_START: 'BOTS_GET_START' = 'BOTS_GET_START';
export const BOTS_GET_ERROR: 'BOTS_GET_ERROR' = 'BOTS_GET_ERROR';
export const BOTS_GET_SUCCESS: 'BOTS_GET_SUCCESS' = 'BOTS_GET_SUCCESS';

export const BOT_GET_SINGLE_START: 'BOT_GET_SINGLE_START' = 'BOT_GET_SINGLE_START';
export const BOT_GET_SINGLE_ERROR: 'BOT_GET_SINGLE_ERROR' = 'BOT_GET_SINGLE_ERROR';
export const BOT_GET_SINGLE_SUCCESS: 'BOT_GET_SINGLE_SUCCESS' = 'BOT_GET_SINGLE_SUCCESS';

export const BOT_CREATE_START: 'BOT_CREATE_START' = 'BOT_CREATE_START';
export const BOT_CREATE_ERROR: 'BOT_CREATE_ERROR' = 'BOT_CREATE_ERROR';
export const BOT_CREATE_SUCCESS: 'BOT_CREATE_SUCCESS' = 'BOT_CREATE_SUCCESS';
