export const BOTS_GET_START: 'BOTS_GET_START' = 'BOTS_GET_START';
export const BOTS_GET_ERROR: 'BOTS_GET_ERROR' = 'BOTS_GET_ERROR';
export const BOTS_GET_SUCCESS: 'BOTS_GET_SUCCESS' = 'BOTS_GET_SUCCESS';
