export const GET_STAGE_START: 'GET_STAGE_START' = 'GET_STAGE_START';
export const GET_STAGE_ERROR: 'GET_STAGE_ERROR' = 'GET_STAGE_ERROR';
export const GET_STAGE_SUCCESS: 'GET_STAGE_SUCCESS' = 'GET_STAGE_SUCCESS';

export const GET_ALL_BOT_STAGES_START: 'GET_ALL_BOT_STAGES_START' = 'GET_ALL_BOT_STAGES_START';
export const GET_ALL_BOT_STAGES_ERROR: 'GET_ALL_BOT_STAGES_ERROR' = 'GET_ALL_BOT_STAGES_ERROR';
export const GET_ALL_BOT_STAGES_SUCCESS: 'GET_ALL_BOT_STAGES_SUCCESS' = 'GET_ALL_BOT_STAGES_SUCCESS';
