export const GET_GROUPS_START: 'GET_GROUPS_START' = 'GET_GROUPS_START';
export const GET_GROUPS_ERROR: 'GET_GROUPS_ERROR' = 'GET_GROUPS_ERROR';
export const GET_GROUPS_SUCCESS: 'GET_GROUPS_SUCCESS' = 'GET_GROUPS_SUCCESS';
