export const GROUPS_GET_START: 'GROUPS_GET_START' = 'GROUPS_GET_START';
export const GROUPS_GET_ERROR: 'GROUPS_GET_ERROR' = 'GROUPS_GET_ERROR';
export const GROUPS_GET_SUCCESS: 'GROUPS_GET_SUCCESS' = 'GROUPS_GET_SUCCESS';
