export const PUSH_POPUP_MESSAGE: 'PUSH_POPUP_MESSAGE' = 'PUSH_POPUP_MESSAGE';
export const POP_POPUP_MESSAGE: 'POP_POPUP_MESSAGE' = 'POP_POPUP_MESSAGE';
export const REMOVE_POPUP_MESSAGE_START: 'REMOVE_POPUP_MESSAGE_START' = 'REMOVE_POPUP_MESSAGE_START';
export const REMOVE_POPUP_MESSAGE_END: 'REMOVE_POPUP_MESSAGE_END' = 'REMOVE_POPUP_MESSAGE_END';
