export const SET_AUTH_TOKENS: 'SET_AUTH_TOKENS' = 'SET_AUTH_TOKENS';

export const LOGIN_START: 'LOGIN_START' = 'LOGIN_START';
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const LOGIN_ERROR: 'LOGIN_ERROR' = 'LOGIN_ERROR';

export const REFRESH_TOKENS_START: 'REFRESH_TOKENS_START' = 'REFRESH_TOKENS_START';
export const REFRESH_TOKENS_ERROR: 'REFRESH_TOKENS_ERROR' = 'REFRESH_TOKENS_ERROR';
export const REFRESH_TOKENS_SUCCESS: 'REFRESH_TOKENS_SUCCESS' = 'REFRESH_TOKENS_SUCCESS';

export const LOGOUT_START: 'LOGOUT_START' = 'LOGOUT_START';
export const LOGOUT_ERROR: 'LOGOUT_ERROR' = 'LOGOUT_ERROR';
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';

export const USER_GET_START: 'USER_GET_START' = 'USER_GET_START';
export const USER_GET_ERROR: 'USER_GET_ERROR' = 'USER_GET_ERROR';
export const USER_GET_SUCCESS: 'USER_GET_SUCCESS' = 'USER_GET_SUCCESS';

export const TRY_AUTH_START: 'TRY_AUTH_START' = 'TRY_AUTH_START';
export const TRY_AUTH_ERROR: 'TRY_AUTH_ERROR' = 'TRY_AUTH_ERROR';
export const TRY_AUTH_SUCCESS: 'TRY_AUTH_SUCCESS' = 'TRY_AUTH_SUCCESS';


export const UPDATE_CREDS: 'UPDATE_CREDS' = 'UPDATE_CREDS';

export const WITH_AUTHENTICATION: 'WITH_AUTHENTICATION' = 'WITH_AUTHENTICATION';
